- name: Initialize Sandbox Host
  hosts: kali-desktop
  gather_facts: yes
  become: yes
  roles:
    - name: user-access
      user_access_username: user
      user_access_password: Password123
      user_access_sudo: True
      
  tasks:
    - name: Print Msg
      debug:
        msg: "kali-2026-sandbox-demo"
